apiVersion: apps/v1
kind: Deployment
metadata:
  # 部署名字
  name: tomcat-deployment
spec:
  replicas: 2
  # 用来查找关联的 Pod，所有标签都匹配才行
  selector:
    matchLabels:
      app: tomcat
  # 定义 Pod 相关数据
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      # 定义容器，可以多个
      containers:
      - name: tomcat # 容器名字
        image: tomcat:9.0
